Inside leadership there are 3 items:
i) Technical Secretory - Antariksh Space Club 
ii) Founding member & Advisory Executive - VYOMA'26
iii) Founding member & Strategic Head - VYOMA'25

these three items have there separate set of images and i don't want to show all of the images at once, so lets show some visual or image and redirect when clicked on respective item to new tab where all the images of respective item will be shown with some description.

A) images for "Technical Secretory - Antariksh Space Club " are inside "Antariksh Space Club" folder(Portfolio\Antariksh Space Club) 
B) images and videos for "Founding member & Advisory Executive - VYOMA'26" are inside "VYOMA 2026" folder(Portfolio\VYOMA 2026)
C) images and videos for "Founding member & Strategic Head - VYOMA'25" are inside "VYOMA 2025" folder(Portfolio\VYOMA 2025)
